baseurl = "https://alexandru-dinu.github.io"
title = "Alexandru Dinu"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en"
paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Alexandru Dinu"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  colorScheme = "auto"
  hidecolorschemetoggle = false

  avatarURL = "images/avatar.jpg"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/alexandru-dinu"
[[params.social]]
  name = "GitLab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/alexandru-dinu"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/alexandrudinu_"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 4
  url = "https://sigmoid.social/@alexd"
[[params.social]]
  name = "StackExchange"
  icon = "fa fa-stack-exchange fa-2x"
  weight = 5
  url = "https://stackexchange.com/users/3783845/alexandru-dinu?tab=accounts"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
