baseURL = "https://alexandru-dinu.github.io"
title = "Alexandru Dinu"
languagecode = "en-us"
defaultcontentlanguage = "en"
paginate = 6
theme = "hugo-coder"
enableEmoji = true
environment = "production"

[markup.highlight]
style = "github-dark"

[params]
author = "Alexandru Dinu"
description = "Alex's personal website"
keywords = "blog,developer,personal"
avatarURL = "images/avatar.jpg"
colorScheme = "auto"
hideColorSchemeToggle = false
katex = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/alexandru-dinu"

[[params.social]]
name = "GitLab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/alexandru-dinu"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/alexandrudinu_"

[[params.social]]
name = "Mastodon"
icon = "fa-brands fa-mastodon fa-2x"
weight = 4
url = "https://sigmoid.social/@alexd"

[[params.social]]
name = "StackExchange"
icon = "fa-brands fa-stack-exchange fa-2x"
weight = 5
url = "https://stackexchange.com/users/3783845/alexandru-dinu?tab=accounts"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"

[[menu.main]]
name = "Projects"
weight = 2
url  = "projects/"

[[menu.main]]
name = "About"
weight = 3
url  = "about/"
